# Installing PyTorch
One of the most preferred ways to install PyTorch is to use Anaconda distribution’s package manager tool – conda. We will create a new environment for this section.

In [ ]:
conda create --name pytorch python=3.8 ipkernel pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch

This will instruct conda to install PyTorch and the required libraries, including cudatoolkit, which provides an environment for creating high-performance gpu-based programming.

After installation, you can perform a simple test to verify that your PyTorch installation works as expected. Run the below Python cell to import torch and verify the PyTorch version.

In [1]:
import torch

torch.__version__

'1.13.0'

# PyTorch Basics
In PyTorch, tensor is a term that refers to any generic  multidimensional array. In practice, tensor establishes a multilinear relationship between the sets of algebraic objects related to a vector space. In PyTorch, tensor is the primary data structure that
encodes the inputs, outputs, as well as the model parameters.

## Creating a Tensor
Tensors are similar to Ndarrays in NumPy. You can create a tensor from a Python’s list or multidimensional lists of lists. You can also create a tensor from an existing NumPy array.

In [2]:
mylist = [1,2,3,4]
mytensor = torch.tensor(mylist)

mytensor

tensor([1, 2, 3, 4])

In [3]:
# Or
import numpy as np

myarr = np.array([[1,2],[3,4]])
mytensor_2 = torch.from_numpy(myarr)
mytensor_2

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

When you create a tensor from a NumPy array, it is not copied to a new memory location – but both the array and tensor share the same memory location. If you make any change in the tensor, it will be reflected in the original array from which it was
created.

In [4]:
mytensor_2[1,1]=5
myarr

array([[1, 2],
       [3, 5]])

Inversely, you can also use mytensor_2.numpy() to return a NumPy array object that shares the same data. Just like NumPy Ndarrays, PyTorch tensors are also homogeneous; that is, all the elements in the tensor have same data type. There are other tensor creation methods similar to NumPy’s array creation methods. This is an example of creating a simple tensor.

In [5]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

This will create a tensor of shape 3x3 with all values as zeros. A similar function in NumPy is np.zeros(3,3). It returns an array of shape 3x3. Though the representation is similar, tensors are the primary unit of data representation in PyTorch. You can use a similar functions to create arrays of ones, or random values of user-defined size.

In [6]:
torch.ones((2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
torch.rand((2,3))

tensor([[0.2377, 0.4087, 0.8049],
        [0.5044, 0.3607, 0.8964]])

## Tensor Operations
PyTorch tensors support several operations in a similar manner as NumPy’s arrays – though the capabilities are more. Arithmetic operations with scalers are broadcasted, that is, applied to all the elements of the tensor. Matrix operations between tensors of compatible shapes are applied in a similar fashion.

In [8]:
myarr = np.array([[1.0,2.0],[3.0,4.0]])
tensor1 = torch.from_numpy(myarr)

tensor1+1

tensor([[2., 3.],
        [4., 5.]], dtype=torch.float64)

In [9]:
tensor1/tensor1

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [10]:
tensor1.sqrt()

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]], dtype=torch.float64)

The functions for describing the data can also be used in a similar manner:

In [11]:
mean, median, min_val, max_val = tensor1.mean(), tensor1.median(), tensor1. min(), tensor1.max()

print ("Statistical Quantities: ")
print ("Mean: {}, \nMedian: {}, \nMinimum: {}, \nMaximum: {}".format(mean, median, min_val, max_val))
print ("The 90-quantile is present at {}".format(tensor1.quantile(0.5)))

Statistical Quantities: 
Mean: 2.5, 
Median: 2.0, 
Minimum: 1.0, 
Maximum: 4.0
The 90-quantile is present at 2.5


This method would concatenate the two tensors. The direction (or axis) of concatenation is provided as the second argument. 0 signifies that the tensors will be joined vertically, and 1 would signify that they will be joined horizontally.

In [12]:
tensor2 = torch.tensor([[5,6],[7,8]])

torch.cat([tensor1, tensor2], 0)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]], dtype=torch.float64)

Other similar functions are hstack and vstack, which can also be used to join two or more tensors horizontally or vertically.

In [13]:
torch.hstack((tensor1,tensor2))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]], dtype=torch.float64)

In [14]:
torch.vstack((tensor1,tensor2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]], dtype=torch.float64)

There’s a reshape function that changes the shape of the tensor. To convert the tensor into a single row with an arbitrary number of columns, we can use shape as (1,-1):

In [15]:
torch.reshape(tensor1, (1, -1))

tensor([[1., 2., 3., 4.]], dtype=torch.float64)