<h1>Universal Functions: Fast Element-Wise Array Functions</h1>

A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

Many ufuncs are simple element-wise transformations, like `numpy.sqrt` or `numpy.exp`:

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [6]:
rng = np.random.default_rng(seed=12345)

These are referred to as unary ufuncs. Others, such as `numpy.add` or `numpy.maximum`, take two arrays (thus, binary ufuncs) and return a single array as the result:

In [7]:
x = rng.standard_normal(8)

y = rng.standard_normal(8)

x

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ])

In [8]:
y

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [9]:
np.maximum(x, y)

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

In this example, `numpy.maximum` computed the element-wise maximum of the elements in `x` and `y`.

While not common, a ufunc can return multiple arrays. `numpy.modf` is one example: a vectorized version of the built-in Python `math.modf`, it returns the fractional and integral parts of a floating-point array:

In [10]:
arr = rng.standard_normal(7) * 5

arr

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [11]:
remainder, whole_part = np.modf(arr)

remainder

array([ 0.94422172, -0.28334067,  0.87928757,  0.99489497,  0.6114903 ,
       -0.49849258,  0.51459671])

In [12]:
whole_part

array([ 3., -6.,  2.,  6.,  6., -1.,  4.])

Ufuncs accept an optional `out` argument that allows them to assign their results into an existing array rather than create a new one:

In [13]:
arr

array([ 3.94422172, -6.28334067,  2.87928757,  6.99489497,  6.6114903 ,
       -1.49849258,  4.51459671])

In [15]:
out = np.zeros_like(arr)
out

array([0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.add(arr, 1)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [17]:
np.add(arr, 1, out=out)

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

In [15]:
out

array([ 4.94422172, -5.28334067,  3.87928757,  7.99489497,  7.6114903 ,
       -0.49849258,  5.51459671])

<b>Note:</b> See some NumPy unary universal functions in this <a href="https://numpy.org/doc/stable/reference/ufuncs.html">link</a>.