<h1> Linear Algebra</h1>

Linear algebra operations, like matrix multiplication, decompositions, determinants, and other square matrix math, are an important part of many array libraries. Multiplying two two-dimensional arrays with `*` is an element-wise product, while matrix multiplications require either using the `dot` function or the `@` infix operator. `dot` is both an array method and a function in the `numpy` namespace for doing matrix multiplication:

In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

y = np.array([[6., 23.], [-1, 7], [8, 9]])

x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [4]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

`x.dot(y)` is equivalent to `np.dot(x, y)`:

In [5]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

A matrix product between a two-dimensional array and a suitably sized one-dimensional array results in a one-dimensional array:

In [6]:
x @ np.ones(3)

array([ 6., 15.])

`numpy.linalg` has a standard set of matrix decompositions and things like inverse and determinant:

In [7]:
rng = np.random.default_rng(seed=12345)

In [8]:
from numpy.linalg import inv, qr

X = rng.standard_normal((5, 5))

mat = X.T @ X

inv(mat)

array([[ 0.15548538, -0.36723081, -0.52638547, -0.2300642 , -0.04646089],
       [-0.36723081,  2.54917814,  3.47827334,  1.48196722,  0.22206454],
       [-0.52638547,  3.47827334,  5.46389554,  2.46214396,  0.63467543],
       [-0.2300642 ,  1.48196722,  2.46214396,  1.38302896,  0.33430132],
       [-0.04646089,  0.22206454,  0.63467543,  0.33430132,  0.33879566]])

In [9]:
mat @ inv(mat)

array([[ 1.00000000e+00, -1.06863236e-16,  1.10504592e-15,
         7.78108190e-17,  6.02310868e-17],
       [ 1.56306273e-16,  1.00000000e+00, -2.04475914e-15,
        -1.12712964e-15, -5.89007500e-16],
       [-3.23287038e-17, -2.21742382e-15,  1.00000000e+00,
         2.15395270e-16,  7.70870846e-17],
       [ 6.18253781e-17,  3.24353009e-16, -1.15703342e-15,
         1.00000000e+00, -2.77603664e-16],
       [ 2.54399270e-16, -6.32605970e-16, -2.56443663e-15,
        -8.36595300e-16,  1.00000000e+00]])

The expression `X.T.dot(X)` computes the dot product of `X` with its transpose `X.T`.

<b>Note:</b> See Commonly used numpy.linalg functions <a href="https://numpy.org/doc/stable/reference/routines.linalg.html">link</a>.